### ISSUE TITLE
Unchecked checkboxes and radio buttons may look disabled to some

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_widgets.dart#377]
The new checkboxes and radio buttons are filled with gray when unchecked, which somehow resembles how some themes and UI toolkits dim disabled checkboxes and radio buttons.

Personally, I got confused while changing the desktop installer to use the new Yaru checkboxes and radio buttons. I thought I did something wrong that caused the checkboxes and radio buttons to become disabled so I thought I'd raise a ticket for consideration because there's a chance that someone else might also misinterpret them. :) Perhaps a subtle frame would help to make it look more interactive?

| Before | After |
|---|---|
| ![Screenshot from 2022-11-11 14-16-31](https://user-images.githubusercontent.com/140617/201348269-4c8ad0c7-4765-4c6a-9c29-435d62da0999.png) | ![Screenshot from 2022-11-11 14-14-41](https://user-images.githubusercontent.com/140617/201348263-156b664d-fcf2-4778-af72-18fbc8b868c3.png) |

Ref: canonical/ubuntu-desktop-installer#1223

**Comment by Feichtmeier** [comment]
Yes, @Jupi007 and we we're discussing this at the summit and asking ourselves if it will grow on us. But I think you are right.

Should we go back to the outline?

**Comment by Jupi007** [comment]
I personally get used to this new design, so it doesn't confuse me.
But some other people can have a different feeling than me :)

As @Feichtmeier said, we're discussing about this at the summit.
The conclusion was that, being used to the material controls, change the design may be confusing for us who was daily interact with material checkradio design.
So maybe should you just get used to this new one @jpnurmi 🙂

But I will also try some other design, just in case:

- use an outline instead of a fully filled box ;
- and with maybe, a brighter fill color (more similar to material, but filled) ;

In fact, I really prefer the filled checkbox design 😄

**Comment by Feichtmeier** [comment]
Yeah that could work
1px stroke outline and super soft background

**Comment by jpnurmi** [comment]
I'm sure I'd eventually get used to it but here's another example where the frameless fill looks somehow confusing to me :upside_down_face: 

![image](https://user-images.githubusercontent.com/140617/201628853-47ea37af-b587-47de-86d3-21f935ba8cd4.png)

**Comment by elioqoshi** [comment]
This is a very nuanced discussion I think, but I will try to give my 2 cents here.

The radio button (at least on dark) used to be more accessible, as the dark gray provided more contrast to orange than white to orange. This might be different on light mode.

How I prefer to do decisions like this is to do a bit of benchmarking with other standard design systems. You can have a look at famous design system components here:
https://component.gallery/components/checkbox/

The vast majority of checkbox components use outlined styling. I'd keep the old style for checkboxes as that's more consistent I'd say.

Regarding radio buttons: I think that's more of a subjective stylistic discussion. I see both styles used in different design systems. However the consistent approach would be for the radio button to be filled (when selected) and have a dark inner dot, instead of white on a dark theme. Otherwise the theming is reversed.

**Comment by elioqoshi** [comment]
@Feichtmeier Yeah indeed. I'd agree with reverting to the old checkbox and tweaking the stroke to 1px. Do you have a preview of how that looks like?

Also regarding radio buttons, the new radio buttons look good, though as mentioned the middle dot should have the color of the background (which on dark theme should be dark gray as well)

**Comment by Feichtmeier** [comment]
No :) Those three new widgets were a solo work by @Jupi007 :) We need to wait until he has time to change this

Question: IF we revert back to 1px outline view, what about the switches then? Jupi made them look perfectly fit to the current yaru gnome switches

![grafik](https://user-images.githubusercontent.com/15329494/201712158-844602f6-1092-4a45-86bd-2f6c406aba81.png)

![grafik](https://user-images.githubusercontent.com/15329494/201712216-910934ae-d6e6-4f64-af70-815c8119e9ba.png)

**Comment by Jupi007** [comment]
Thanks everybody for your feedback 🙂

I'm currently creating a few mockups to explore some other ideas. I will also maybe push a branch for testing.
But indeed, I really think we should go with an outline.

**Comment by Jupi007** [comment]
I tried and tested a lot a thing. So here is a first mockup, of how it could look with a border and a soft background (please look at 100% to avoid blur):

![checkboxes](https://user-images.githubusercontent.com/36476595/202272058-16c7c511-6a88-40b3-927b-649c2b6f170c.png)

If you like this design, I will implement it in a branch so we can test it in real situation.

**Comment by Jupi007** [comment]
@elioqoshi I also tried to use the background color in the inner radio circle:

![image1746](https://user-images.githubusercontent.com/36476595/202274255-a1be9f6c-448b-4574-8009-98f99abf4895.png)

But I don't like it honestly, and it is not consistent with the other controls.

**Comment by Feichtmeier** [comment]
> I tried and tested a lot a thing. So here is a first mockup, of how it could look with a border and a soft background (please look at 100% to avoid blur):
> 
> ![checkboxes](https://user-images.githubusercontent.com/36476595/202272058-16c7c511-6a88-40b3-927b-649c2b6f170c.png)
> 
> If you like this design, I will implement it in a branch so we can test it in real situation.
> 
> Edit: I really like this bordered look :p

This looks much better!
Eventually I would go even further in lightening up the background? I am unsure, even though in this picture they look awesome, how heavy they look in the context of a real UI

**Comment by Jupi007** [comment]
> This looks much better!
> Eventually I would go even further in lightening up the background? I am unsure, even though in this picture they look awesome, how heavy they look in the context of a real UI

Maybe we can lighten a little the background, but really a little, because it looks weird when it's too much.
The maximum I can do is this imo:

![checkboxes](https://user-images.githubusercontent.com/36476595/202280713-84cd0874-77c8-4e38-b7a6-4ba2b543bf8f.png)

And I think it looks good.

As you like this design, I'll create a test branch so we can see how it looks in situation :)

**Comment by Feichtmeier** [comment]
awesome, thank you very much, this looks like a shitload of work!

**Comment by jpnurmi** [comment]
Great improvements! Thank you @Jupi007 and everyone else who was involved!
