### ISSUE TITLE
Wrongly colored separator

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru_widgets.dart#522]
Forwarded from https://github.com/ubuntu-flutter-community/software/issues/766

![image](https://user-images.githubusercontent.com/3986894/212492678-abe716ac-64b5-42f2-ade3-7f4bb79ed9a6.png)

**Comment by Feichtmeier** [comment]
@madsrh hello again

Could you check if this

1) happens with 22.04
2) happens if you fully upgrade your 22.10 ?

**Comment by madsrh** [comment]
> Could you check if this happens with 22.04

Ahhh, you called it @Feichtmeier 🥇 There's no issue in 22.04, only 22.10 and 23.04 daily

**Comment by Feichtmeier** [comment]
This means that they still did not fix this issue.... 

From where did you switch the theme? Shell or gnome control center?

**Comment by madsrh** [comment]
> From where did you switch the theme? Shell or gnome control center?

Ahh, if I use the dark theme from appearance in Settings there's no issue, but using the light theme and switching inside Software, the line returns.

**Comment by Feichtmeier** [comment]
> > From where did you switch the theme? Shell or gnome control center?
> 
> Ahh, if I use the dark theme from appearance in Settings there's no issue, but using the light theme and switching inside Software, the line returns.

Ohhh 😮


@wiskeypeak could you taste a look please.

**Comment by whiskeyPeak** [comment]
Ahhh, I think I see what's going on. When changing the theme from the shell itself, my guess is that the default background colour of GTK apps change as well, so it is white in light mode and grey in dark mode. Changing the theme in the software centre app only changes the theme of what Flutter draws, so the background colour of the GTK app (which lies under the flutter renderer) stays white.

We still see the white line because Flutter hasn't drawn anything above that specific part of the GTK window. Like I said in https://github.com/ubuntu-flutter-community/software/issues/766#issuecomment-1382651527, adding a scaffold should fix this :D

@madsrh Could you run the latest example from yaru_widgets.dart and see if the issue is reproduceable there? Thanks!
