### ISSUE TITLE
Rename `YaruMasterDetailBuilder` into `YaruMasterDetailTileBuilder`?

### ISSUE THREAD

**Issue by Jupi007** [ubuntu/yaru_widgets.dart#709]
Shouldn't `YaruMasterDetailBuilder` be named `YaruMasterDetailTileBuilder`?
              Imo, it would be more logical.

CC @Feichtmeier @jpnurmi 

_Originally posted by @Jupi007 in https://github.com/ubuntu/yaru_widgets.dart/issues/708#issuecomment-1596194374_

**Comment by jpnurmi** [comment]
I recall the builder was initially used for building both icons and titles. That's probably why the name was chosen to include both "master" and "detail" because titles were used on both sides, in the master list, and on the detail page. Now that there's a separate builder for master tiles and detail pages, and this builder is only used for master tiles, one option could be to name it `YaruMasterTileBuilder`.

**Comment by Jupi007** [comment]
Indeed, I had forgotten it was use in those two places.
And `YaruMasterTileBuilder` sounds better :+1:
